<a href="https://colab.research.google.com/github/lavanyaSBeulah/The-Sparks-Foundation/blob/main/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data preprocessing steps on the given array



In [ ]:
import numpy as np
from sklearn import preprocessing

In [ ]:
input_data = np.array([[3, -1.5, 3, -6.4], [0, 3, -1.3, 4.1], [1, 2.3, -2.9, -4.3]])

# 1.**MEAN** **REMOVAL**

In [ ]:
data_standardized = preprocessing.scale(input_data)
print ("\n Mean = ", data_standardized.mean(axis = 1))
print ("Std deviation = ", data_standardized.std(axis = 1))


 Mean =  [ 0.09396578  0.20878489 -0.30275067]
Std deviation =  [1.26770138 0.97419036 0.54754697]


# **2.SCALE THE DATA**

In [ ]:
data_scaler = preprocessing.MinMaxScaler(feature_range = (0, 1))
data_scaled = data_scaler.fit_transform(input_data)
print ("\n Min max scaled data = ", data_scaled)


 Min max scaled data =  [[1.         0.         1.         0.        ]
 [0.         1.         0.27118644 1.        ]
 [0.33333333 0.84444444 0.         0.2       ]]


## 3.**Normalize the data**

In [ ]:
data_normalized = preprocessing.normalize(input_data, norm  = 'l1')
print ("\nL1 normalized data = ", data_normalized)


L1 normalized data =  [[ 0.21582734 -0.10791367  0.21582734 -0.46043165]
 [ 0.          0.35714286 -0.1547619   0.48809524]
 [ 0.0952381   0.21904762 -0.27619048 -0.40952381]]


## **4.Binarize the data**

In [ ]:
data_binarized = preprocessing.Binarizer(threshold=1.4).transform(input_data)
print ("\nBinarized data =", data_binarized)


Binarized data = [[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 0. 0.]]
